apiVersion: apps/v1
kind: Deployment
metadata:
  name: material-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: material-app
  template:
    metadata:
      labels:
        app: material-app
    spec:
      containers:
      - name: material-app
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag}}
        ports:
        - containerPort: 80
